name: Deploy to Azure

on:
  workflow_run:
  workflows: ["Build & push Docker image to Github Container Registry"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Copy docker compose to VM
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          # Prefer SSH private key if provided in secrets, otherwise fall back to password
          private_key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          port: 22
          source: "compose.yaml"
          target: "/home/${{ secrets.AZURE_VM_USERNAME }}"

      - name: Deploy on VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          private_key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          port: 22
          script: |
            cd /home/${{ secrets.AZURE_VM_USERNAME }}
            docker compose pull
            docker compose up -d --remove-orphans
